interface Resources {
  "apps": {
    "page.title": "App Integrations",
    "page.description": "Here's a list of your apps for the integration!",
    "filter.placeholder": "Filter apps...",
    "select.all": "All Apps",
    "select.connected": "Connected",
    "select.notConnected": "Not Connected",
    "button.connect": "Connect",
    "button.connected": "Connected",
    "sort.ascending": "Ascending",
    "sort.descending": "Descending",
    "banner.comingSoon": "Coming Soon...",
    "desc.telegram": "Connect with Telegram for real-time communication.",
    "desc.notion": "Effortlessly sync Notion pages for seamless collaboration.",
    "desc.figma": "View and collaborate on Figma designs in one place.",
    "desc.trello": "Sync Trello cards for streamlined project management.",
    "desc.slack": "Integrate Slack for efficient team communication.",
    "desc.zoom": "Host Zoom meetings directly from the dashboard.",
    "desc.stripe": "Easily manage Stripe transactions and payments.",
    "desc.gmail": "Access and manage Gmail messages effortlessly.",
    "desc.medium": "Explore and share Medium stories on your dashboard.",
    "desc.skype": "Connect with Skype contacts seamlessly.",
    "desc.docker": "Effortlessly manage Docker containers on your dashboard.",
    "desc.github": "Streamline code management with GitHub integration.",
    "desc.gitlab": "Efficiently manage code projects with GitLab integration.",
    "desc.discord": "Connect with Discord for seamless team communication.",
    "desc.whatsapp": "Easily integrate WhatsApp for direct messaging."
  },
  "auth": {
    "signInTitle": "Login",
    "signInSubtitle": "Enter your email and password below to log into your account",
    "email": "Email",
    "emailPlaceholder": "name@example.com",
    "password": "Password",
    "passwordPlaceholder": "********",
    "forgotPassword": "Forgot password?",
    "login": "Login",
    "loggingIn": "Logging in...",
    "loginSuccess": "Login successful! Welcome back.",
    "loginFailed": "Login failed",
    "orContinueWith": "Or continue with",
    "google": "Google",
    "facebook": "Facebook",
    "twitter": "Twitter",
    "termsAndPrivacy": "By clicking login, you agree to our Terms of Service and Privacy Policy.",
    "appName": "Tutti",
    "forgotPasswordTitle": "Forgot Password",
    "forgotPasswordSubtitle": "Enter your registered email and we will send you a link to reset your password.",
    "continue": "Continue",
    "dontHaveAccount": "Don't have an account?",
    "alreadyHaveAccount": "Already have an account?",
    "confirmPassword": "Confirm Password",
    "signUp": "Sign up",
    "signUpSubtitle": "Enter your email and password to create an account.",
    "usernamePlaceholder": "Enter your username",
    "signUpSuccess": "Sign up successful!",
    "signUpFailed": "Sign up failed"
  },
  "common": {
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "deleteAll": "Delete All",
    "edit": "Edit",
    "search": "Search",
    "add": "Add",
    "close": "Close",
    "open": "Open",
    "import": "Import",
    "export": "Export",
    "create": "Create",
    "createNew": "Create New",
    "update": "Update",
    "viewAll": "View All",
    "reset": "Reset",
    "creating": "Creating...",
    "updating": "Updating...",
    "deleting": "Deleting...",
    "logout": "Log Out",
    "thisWeek": "This Week",
    "thisMonth": "This Month",
    "thisYear": "This Year",
    "allTime": "View All Time",
    "last7days": "Last 7 Days",
    "last30days": "Last 30 Days",
    "last90days": "Last 90 Days",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "info": "Info",
    "continue": "Continue",
    "changeLanguage": "Change Language",
    "toggleTheme": "Toggle Theme",
    "themeLight": "Light",
    "themeDark": "Dark",
    "themeSystem": "System",
    "languageEn": "English",
    "languageVi": "Tiếng Việt",
    "table.sortAsc": "Sort ascending",
    "table.sortDesc": "Sort descending",
    "table.sortAscLabel": "Sorted ascending. Click to sort descending.",
    "table.sortDescLabel": "Sorted descending. Click to sort ascending.",
    "table.sortNoneLabel": "Not sorted. Click to sort ascending.",
    "table.hideColumn": "Hide column",
    "table.selectedRows": "{{count}} of {{total}} rows selected",
    "table.rowsPerPage": "Rows per page",
    "table.pageInfo": "Page {{current}} of {{total}}",
    "table.firstPage": "Go to first page",
    "table.previousPage": "Go to previous page",
    "table.nextPage": "Go to next page",
    "table.lastPage": "Go to last page",
    "table.view": "View",
    "table.toggleColumns": "Toggle columns",
    "dialog.importDesc": "Quickly import data from a CSV file.",
    "dialog.createDesc": "Add new data by providing the necessary information. Press save when you're done.",
    "dialog.updateDesc": "Update data by providing the necessary information. Press save when you're done.",
    "dialog.deleteConfirm": "Are you sure you want to delete this item? This action cannot be undone.",
    "dialog.deleteTitle": "Delete: {{title}}",
    "form.uploadFile": "Please upload a file",
    "form.csvFormat": "Please upload a csv format.",
    "message.saveSuccess": "Saved successfully",
    "message.saveError": "Could not save",
    "message.generating": "Generating...",
    "termsOfService": "Terms of Service",
    "privacyPolicy": "Privacy Policy",
    "clearFilters": "Clear filters"
  },
  "dashboard": {
    "welcome": "Welcome Back, {{name}}!",
    "description": "Here's an overview of your team's project activity today",
    "chart.taskCompletionOverview": "Task Completion Overview",
    "chart.completed": "Completed",
    "chart.inProgress": "In Progress",
    "topEmployees": "Top Performing Employees",
    "recentTasks": "Recent Tasks",
    "recentTasks.task": "Task",
    "recentTasks.assignedTo": "Assigned To",
    "recentTasks.project": "Project",
    "recentTasks.dueDate": "Due Date",
    "recentTasks.status": "Status",
    "activeProjects": "Active Projects",
    "kpi.totalProjects": "Total Projects",
    "kpi.tasksCompleted": "Tasks Completed",
    "kpi.tasksInProgress": "Tasks In Progress",
    "kpi.overdueTasks": "Overdue Tasks",
    "kpi.activeEmployees": "Active Employees",
    "kpi.changeText.thisMonth": "(+1 this month)",
    "kpi.changeText.percent": "(+17%)",
    "kpi.changeText.minus": "(-2)",
    "kpi.changeText.plus": "(+2)",
    "employee.id": "Employee ID: {{id}}",
    "employee.sales": "{{count}} Tasks Completed",
    "project.orders": "{{count}} Tasks Active"
  },
  "glossary": {
    "task": "Task",
    "tasks": "Tasks",
    "project": "Project",
    "projects": "Projects",
    "admin": "Admin",
    "user": "User",
    "name": "Name",
    "username": "Username",
    "status": "Status",
    "priority": "Priority",
    "assignee": "Assignee",
    "description": "Description",
    "startDate": "Start Date",
    "dueDate": "Due Date",
    "donePct": "Progress",
    "completionPct": "Completion %",
    "title": "Title",
    "role": "Role",
    "email": "Email",
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "createdAt": "Created At",
    "updatedAt": "Updated At",
    "createdBy": "Created By",
    "updatedBy": "Updated By",
    "status.open": "Open",
    "status.inprogress": "In Progress",
    "status.resolved": "Resolved",
    "status.completed": "Completed",
    "status.active": "Active",
    "status.paused": "Paused",
    "status.cancelled": "Cancelled",
    "status.inactive": "Inactive",
    "status.suspended": "Suspended",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",
    "date": "Date",
    "date.start": "Start Date",
    "date.due": "Due Date",
    "progress": "Progress",
    "table": "Table",
    "actions": "Actions",
    "form.enterTitle": "Enter title",
    "form.selectProject": "Select project",
    "form.enterDescription": "Enter description",
    "form.selectStatus": "Select status",
    "form.selectPriority": "Select priority",
    "form.selectStartDate": "Select start date",
    "form.selectDueDate": "Select due date",
    "form.selectAssignee": "Select assignee",
    "form.selectRole": "Select role",
    "form.enterEmail": "Enter email",
    "form.enterPassword": "Enter password",
    "form.enterConfirmPassword": "Enter confirm password",
    "general": "General",
    "other": "Other",
    "dashboard": "Dashboard",
    "apps": "Apps",
    "chats": "Chats",
    "users": "Users",
    "settings": "Settings",
    "helpCenter": "Help Center",
    "profile": "Profile",
    "account": "Account",
    "appearance": "Appearance",
    "notifications": "Notifications",
    "display": "Display",
    "teams": "Teams",
    "addTeam": "Add Team",
    "simplifyYourWorkflow": "Simplify your workflow",
    "enterprise": "Enterprise",
    "startup": "Startup",
    "selectStartDate": "Select start date",
    "selectDueDate": "Select due date"
  },
  "projects": {
    "page.title": "Projects",
    "page.description": "Manage your projects and track their progress.",
    "filter.placeholder": "Filter projects...",
    "dialog.create.title": "Create Project",
    "dialog.create.description": "Fill in the details below to create a new project.",
    "dialog.edit.title": "Edit Project",
    "dialog.edit.description": "Update the project details below.",
    "dialog.delete.title": "Delete Project",
    "dialog.delete.description": "Are you sure you want to delete \"{{name}}\"? This action cannot be undone.",
    "form.name.placeholder": "Enter project name",
    "form.description.placeholder": "Enter project description",
    "button.create": "Create Project",
    "button.update": "Update Project",
    "button.delete": "Delete Project",
    "message.success.created": "Project created successfully",
    "message.success.updated": "Project updated successfully",
    "message.success.deleted": "Project deleted successfully",
    "message.error.createFailed": "Failed to create project",
    "message.error.updateFailed": "Failed to update project",
    "message.error.deleteFailed": "Failed to delete project",
    "mockGerpData": "Mock GERP Data"
  },
  "tasks": {
    "page.title": "Tasks",
    "page.description": "Here is your list of tasks for this month!",
    "filter.placeholder": "Filter tasks...",
    "dialog.create.title": "Create Task",
    "dialog.create.description": "Add a new task by providing the necessary information. Press save when you're done.",
    "dialog.update.title": "Update Task",
    "dialog.update.description": "Update task by providing the necessary information. Press save when you're done.",
    "message.success.saved": "Task saved successfully",
    "message.error.saveFailed": "Failed to save task",
    "message.success.updated": "Task updated successfully",
    "message.success.deleted": "Task deleted successfully",
    "message.success.completed": "Task completed successfully",
    "message.success.assigned": "Task assigned successfully",
    "mockGerpTasks": "Mock Gerp Tasks",
    "calendarView": "Calendar View",
    "listView": "List View"
  },
  "users": {
    "page.title": "User List",
    "page.description": "Manage your users and their roles here.",
    "filter.placeholder": "Filter users...",
    "addUser": "Add User",
    "inviteUser": "Invite User",
    "inviteUserDescription": "Invite new user to join your team by sending them an email invitation. Assign a role to define their access level.",
    "dialog.create.title": "Create User",
    "dialog.create.description": "Fill in the details below to create a new user.",
    "dialog.edit.title": "Edit User",
    "dialog.edit.description": "Update the user details below.",
    "dialog.delete.title": "Delete User",
    "dialog.delete.description": "Are you sure you want to delete \"{{name}}\"? This action cannot be undone.",
    "form.name.placeholder": "Enter user name",
    "form.enterDescriptionPlaceholder": "Add a personal note to your invitation (optional)",
    "message.success.created": "User created successfully",
    "message.success.updated": "User updated successfully",
    "message.success.deleted": "User deleted successfully",
    "message.error.createFailed": "Failed to create user",
    "message.error.updateFailed": "Failed to update user",
    "message.error.deleteFailed": "Failed to delete user"
  },
  "validation": {
    "required": "This field is required",
    "usernameRequired": "Please enter your username",
    "emailRequired": "Please enter your email",
    "passwordRequired": "Please enter your password",
    "invalidEmail": "Email is invalid",
    "minLengthPassword": "Password must be at least 8 characters long",
    "minLowercasePassword": "Password must contain at least one lowercase letter",
    "minNumberPassword": "Password must contain at least one number",
    "passwordsDoNotMatch": "Passwords do not match",
    "passwordMinLength": "Password must be at least 7 characters long"
  }
}

export default Resources;
