interface Resources {
  "auth": {
    "signInTitle": "Login",
    "signInSubtitle": "Enter your email and password below to log into your account",
    "email": "Email",
    "emailPlaceholder": "name@example.com",
    "password": "Password",
    "passwordPlaceholder": "********",
    "forgotPassword": "Forgot password?",
    "login": "Login",
    "loggingIn": "Logging in...",
    "loginSuccess": "Login successful! Welcome back.",
    "loginFailed": "Login failed",
    "orContinueWith": "Or continue with",
    "google": "Google",
    "facebook": "Facebook",
    "twitter": "Twitter",
    "termsAndPrivacy": "By clicking login, you agree to our Terms of Service and Privacy Policy.",
    "appName": "Tutti",
    "forgotPasswordTitle": "Forgot Password",
    "forgotPasswordSubtitle": "Enter your registered email and we will send you a link to reset your password.",
    "continue": "Continue",
    "dontHaveAccount": "Don't have an account?",
    "alreadyHaveAccount": "Already have an account?",
    "confirmPassword": "Confirm Password",
    "signUp": "Sign up",
    "signUpSubtitle": "Enter your email and password to create an account.",
    "usernamePlaceholder": "Enter your username",
    "signUpSuccess": "Sign up successful!",
    "signUpFailed": "Sign up failed",
    "signOutSuccess": "Sign out successful!",
    "signOutFailed": "Sign out failed"
  },
  "common": {
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "deleteAll": "Delete All",
    "edit": "Edit",
    "search": "Search",
    "add": "Add",
    "close": "Close",
    "open": "Open",
    "import": "Import",
    "export": "Export",
    "create": "Create",
    "createNew": "Create New",
    "update": "Update",
    "invite": "Invite",
    "inviteEmail": "Invite Email",
    "view": "View",
    "viewDetail": "View Detail",
    "viewAll": "View All",
    "reset": "Reset",
    "activate": "Activate",
    "creating": "Creating...",
    "updating": "Updating...",
    "deleting": "Deleting...",
    "suspend": "Suspend",
    "confirm": "Confirm",
    "logout": "Log Out",
    "thisWeek": "This Week",
    "thisMonth": "This Month",
    "thisYear": "This Year",
    "allTime": "View All Time",
    "last7days": "Last 7 Days",
    "last30days": "Last 30 Days",
    "last90days": "Last 90 Days",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "info": "Info",
    "continue": "Continue",
    "changeLanguage": "Change Language",
    "toggleTheme": "Toggle Theme",
    "themeLight": "Light",
    "themeDark": "Dark",
    "themeSystem": "System",
    "languageEn": "English",
    "languageVi": "Tiếng Việt",
    "table.sortAsc": "Sort ascending",
    "table.sortDesc": "Sort descending",
    "table.sortAscLabel": "Sorted ascending. Click to sort descending.",
    "table.sortDescLabel": "Sorted descending. Click to sort ascending.",
    "table.sortNoneLabel": "Not sorted. Click to sort ascending.",
    "table.hideColumn": "Hide column",
    "table.selectedRows": "{{count}} of {{total}} rows selected",
    "table.rowsPerPage": "Rows per page",
    "table.pageInfo": "Page {{current}} of {{total}}",
    "table.firstPage": "Go to first page",
    "table.previousPage": "Go to previous page",
    "table.nextPage": "Go to next page",
    "table.lastPage": "Go to last page",
    "table.view": "View",
    "table.toggleColumns": "Toggle columns",
    "dialog.importDesc": "Quickly import data from a CSV file.",
    "dialog.createDesc": "Add new data by providing the necessary information. Press save when you're done.",
    "dialog.updateDesc": "Update data by providing the necessary information. Press save when you're done.",
    "dialog.deleteConfirm": "Please be carefully, this operation can not be rolled back.",
    "dialog.deleteTitle": "Delete: {{title}}",
    "form.uploadFile": "Please upload a file",
    "form.csvFormat": "Please upload a csv format.",
    "message.saveSuccess": "Saved successfully",
    "message.saveError": "Could not save",
    "message.generating": "Generating...",
    "termsOfService": "Terms of Service",
    "privacyPolicy": "Privacy Policy",
    "clearFilters": "Clear filters",
    "backToTop": "Back to top",
    "notProvided": "Not Provided",
    "viewOnMap": "View on Map",
    "viewContract": "View Contract"
  },
  "dashboard": {
    "welcome": "Welcome Back, {{name}}!",
    "description": "Here's an overview of your team's project activity today",
    "chart.taskCompletionOverview": "Task Completion Overview",
    "chart.completed": "Completed",
    "chart.inProgress": "In Progress",
    "topEmployees": "Top Performing Employees",
    "recentTasks": "Recent Tasks",
    "recentTasks.task": "Task",
    "recentTasks.assignedTo": "Assigned To",
    "recentTasks.project": "Project",
    "recentTasks.dueDate": "Due Date",
    "recentTasks.status": "Status",
    "activeProjects": "Active Projects",
    "kpi.totalProjects": "Total Projects",
    "kpi.tasksCompleted": "Tasks Completed",
    "kpi.tasksInProgress": "Tasks In Progress",
    "kpi.overdueTasks": "Overdue Tasks",
    "kpi.activeEmployees": "Active Employees",
    "kpi.changeText.thisMonth": "(+1 this month)",
    "kpi.changeText.percent": "(+17%)",
    "kpi.changeText.minus": "(-2)",
    "kpi.changeText.plus": "(+2)",
    "employee.id": "Employee ID: {{id}}",
    "employee.sales": "{{count}} Tasks Completed",
    "project.orders": "{{count}} Tasks Active"
  },
  "employee": {
    "page": {
      "title": "Employees",
      "description": "Manage your company employees",
      "personalInformation": "Personal Information",
      "contactInformation": "Contact Information",
      "addressInformation": "Address Information",
      "personalContact": "Personal Contact",
      "otherContact": "Other Contact",
      "residentialAddress": "Residential Address",
      "citizenIdAddress": "Citizen ID Address",
      "notes": "Notes",
      "tags": "Tags",
      "employmentOverview": "Employment Overview",
      "lastClockedIn": "Last Clocked In",
      "lastMessaged": "Last Messaged",
      "employeeId": "Employee ID",
      "aFewSecondsAgo": "A few seconds ago",
      "twoDaysAgo": "2 Days ago"
    },
    "tabs": {
      "personal": "Personal Information",
      "contract": "Contract",
      "payroll": "Payroll",
      "time": "Time Management",
      "assets": "Assets",
      "document": "Document",
      "training": "Training",
      "finance": "Finance"
    },
    "actions": {
      "addEmployee": "Add Employee",
      "addTag": "Add Tag",
      "sendEmail": "Send Email"
    },
    "employmentType": {
      "fulltime": "Full Time",
      "parttime": "Part Time",
      "contract": "Contract",
      "intern": "Intern",
      "freelance": "Freelance"
    },
    "role": {
      "fe_developer": "Frontend Developer",
      "be_developer": "Backend Developer",
      "fullstack_developer": "Full Stack Developer",
      "mobile_developer": "Mobile Developer",
      "qa": "QA",
      "hr": "HR",
      "designer": "Designer",
      "accountant": "Accountant"
    },
    "level": {
      "entry": "Entry",
      "junior": "Junior",
      "mid": "Mid",
      "senior": "Senior",
      "lead": "Lead",
      "manager": "Manager",
      "director": "Director",
      "executive": "Executive"
    },
    "department": {
      "qa": "QA",
      "it": "IT",
      "hr": "HR",
      "finance": "Finance",
      "marketing": "Marketing"
    },
    "form": {
      "searchEmployees": "Search employees",
      "enterFirstName": "Enter First Name",
      "enterLastName": "Enter Last Name",
      "enterReligion": "Enter Religion",
      "enterPlaceOfBirth": "Enter Place of Birth",
      "selectGender": "Select Gender",
      "selectMaritalStatus": "Select Marital Status",
      "selectBirthdate": "Select Birthdate",
      "selectBloodType": "Select Blood Type",
      "enterPhoneNumber": "Enter Phone Number",
      "enterEmail": "Enter Email",
      "enterEmergencyContact": "Enter Emergency Contact",
      "enterEmergencyPhone": "Enter Emergency Phone",
      "enterRelationship": "Enter Relationship",
      "enterResidentialAddress": "Enter Residential Address",
      "enterCitizenIdAddress": "Enter Citizen ID Address",
      "enterNotes": "Enter Notes",
      "selectStartDate": "Select Start Date",
      "selectJobRole": "Select Job Role",
      "selectJobLevel": "Select Job Level",
      "selectEmploymentType": "Select Employment Type",
      "selectDepartment": "Select Department"
    },
    "messages": {
      "noEmployeesFound": "No employees found matching your criteria.",
      "employeeDeleted": "Employee deleted successfully",
      "employeeUpdated": "Employee updated successfully",
      "employeeCreated": "Employee created successfully",
      "deleteConfirmation": "Are you sure you want to delete this employee?",
      "payrollNotAvailable": "Payroll information is not available in this demo."
    }
  },
  "glossary": {
    "form": {
      "enterDescription": "Enter description",
      "enterEmail": "Enter email",
      "enterPassword": "Enter password",
      "enterConfirmPassword": "Enter confirm password",
      "selectRole": "Select role",
      "selectCreatedAtFrom": "Select created at from",
      "selectCreatedAtTo": "Select created at to"
    },
    "task": "Task",
    "tasks": "Tasks",
    "project": "Project",
    "projects": "Projects",
    "admin": "Admin",
    "user": "User",
    "employee": "Employee",
    "recruiter": "Recruiter",
    "hiringManager": "Hiring Manager",
    "hrManager": "HR Manager",
    "superAdmin": "Super Admin",
    "organization": "Organization",
    "employees": "Employees",
    "structure": "Structure",
    "report": "Report",
    "name": "Name",
    "username": "Username",
    "fullName": "Full Name",
    "firstName": "First Name",
    "lastName": "Last Name",
    "contact": "Contact",
    "team": "Team",
    "jobTitle": "Job Title",
    "phone": "Phone",
    "dateJoined": "Date Joined",
    "status": "Status",
    "priority": "Priority",
    "assignee": "Assignee",
    "description": "Description",
    "startDate": "Start Date",
    "dueDate": "Due Date",
    "donePct": "Progress",
    "completionPct": "Completion %",
    "title": "Title",
    "role": "Role",
    "email": "Email",
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "createdAt": "Created At",
    "updatedAt": "Updated At",
    "createdBy": "Created By",
    "updatedBy": "Updated By",
    "date": "Date",
    "table": "Table",
    "actions": "Actions",
    "general": "General",
    "other": "Other",
    "dashboard": "Dashboard",
    "apps": "Apps",
    "chats": "Chats",
    "users": "Users",
    "settings": "Settings",
    "helpCenter": "Help Center",
    "profile": "Profile",
    "account": "Account",
    "appearance": "Appearance",
    "notifications": "Notifications",
    "display": "Display",
    "createdAtFrom": "Created At From",
    "createdAtTo": "Created At To",
    "employeeName": "Employee Name",
    "type": "Type",
    "department": "Department",
    "jobRole": "Job Role",
    "dateStarted": "Date Joined",
    "employmentType": "Type",
    "joinAt": "Join At",
    "gender": "Gender",
    "maritalStatus": "Marital Status",
    "religion": "Religion",
    "placeOfBirth": "Place of Birth",
    "birthdate": "Birthdate",
    "bloodType": "Blood Type",
    "age": "Age",
    "emergencyContact": "Emergency Contact",
    "emergencyPhone": "Emergency Phone",
    "relationship": "Relationship",
    "phoneNumber": "Phone Number",
    "notProvided": "Not Provided",
    "jobLevel": "Job Level",
    "employmentStatus": "Employment Status"
  },
  "users": {
    "page.title": "User List",
    "page.description": "Manage your users and their roles here.",
    "filter.username.placeholder": "Search user names",
    "addUser": "Add User",
    "createRandomUsers": "Create Random Users",
    "inviteUser": "Invite User",
    "deleteUsers": "Delete Users ({{count}})",
    "inviteUserDescription": "Invite new user to join your team by sending them an email invitation. Assign a role to define their access level.",
    "suspendDescription": "Are you sure you want to suspend <strong>{{name}}</strong>?<br/> This action will prevent the user from logging in to the system.",
    "dialog.create.title": "Create User",
    "dialog.create.description": "Fill in the details below to create a new user.",
    "dialog.edit.title": "Edit User",
    "dialog.edit.description": "Update the user details below.",
    "dialog.delete.title": "Delete User",
    "dialog.delete.description": "Are you sure you want to delete <strong>{{name}}</strong>?<br/> This action will permanently remove the user from the system. This cannot be undone.",
    "dialog.delete.confirm": "Are you sure you want to delete <strong>{{count}}</strong> users?<br/> This action will permanently remove the users from the system. This cannot be undone.",
    "form": {
      "enterFirstName": "Enter First Name",
      "enterLastName": "Enter Last Name",
      "enterEmail": "Enter Email",
      "selectRole": "Select Role",
      "enterPassword": "Enter Password",
      "confirmPassword": "Confirm Password",
      "enterDescriptionPlaceholder": "Add a personal note to your invitation (optional)"
    },
    "message.success.created": "User created successfully",
    "message.success.updated": "User updated successfully",
    "message.success.deleted": "User deleted successfully",
    "message.success.suspended": "User suspended successfully",
    "message.success.activated": "User activated successfully",
    "message.success.deletedMany": "Users deleted successfully",
    "message.success.createdMany": "Users created successfully",
    "message.error.createFailed": "Failed to create user",
    "message.error.updateFailed": "Failed to update user",
    "message.error.deleteFailed": "Failed to delete user",
    "message.error.suspendFailed": "Failed to suspend user",
    "message.error.activateFailed": "Failed to activate user",
    "message.error.deleteManyFailed": "Failed to delete users",
    "message.error.createManyFailed": "Failed to create users",
    "role": {
      "admin": "Admin",
      "employee": "Employee",
      "recruiter": "Recruiter",
      "hiringManager": "Hiring Manager",
      "hrManager": "HR Manager",
      "superAdmin": "Super Admin"
    },
    "status": {
      "active": "Active",
      "inactive": "Inactive",
      "notVerified": "Not Verified",
      "suspended": "Suspended"
    },
    "gender": {
      "male": "Male",
      "female": "Female",
      "other": "Other"
    },
    "maritalStatus": {
      "single": "Single",
      "married": "Married",
      "divorced": "Divorced",
      "widowed": "Widowed"
    }
  },
  "validation": {
    "required": "This field is required",
    "usernameRequired": "Please enter your username",
    "emailRequired": "Please enter your email",
    "passwordRequired": "Please enter your password",
    "invalidEmail": "Email is invalid",
    "minLengthPassword": "Password must be at least 8 characters long",
    "minLowercasePassword": "Password must contain at least one lowercase letter",
    "minNumberPassword": "Password must contain at least one number",
    "passwordsDoNotMatch": "Passwords do not match",
    "passwordMinLength": "Password must be at least 7 characters long"
  }
}

export default Resources;
